spring:
  application:
    name: harvest_trading
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
  redis:
    host: 123.58.213.158
    port: 6020
    database: 1
    password: iphone5C,.
    timeout: 10000
    lettuce:
      pool:
        max-idle: -1 # 连接池中的最大空闲连接
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-active: 50 # 连接池最大连接数（使用负值表示没有限制）
        min-idle: 0 # 连接池中的最小空闲连接

  mail:
    host: smtp.qq.com
    protocol: smtp
    username: liwei.job@foxmail.com
    password: urpoikarjrofbaej
    properties:
      smtp:
        auth: false
        starttls:
          enable: false
          required: false
      mail:
        smtp:
          ssl:
            enable: true
logging:
  file:
    path: /usr/local/var/www/java_log/
  config: classpath:logback-spring.xml
  level:
    root: error
    org:
      springframework: error
    com:
      contract:
        harvest: info
huobi:
  api_key: ghxertfvbf-5e9a8e8a-677d8036-56da3
  secret_key: 40f6ad9d-3793f4d9-a6cb515a-13530
